package com.nevoit.cresto.data.todo

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

enum class TodoReminderMode {
    BeforeStart,
    BeforeDueDate
}

/**
 * Represents a single to-do item entity for the Room database.
 *
 * @property id The unique identifier for the to-do item. Auto-generated by the database.
 * @property title The main text or title of the to-do item.
 * @property dueDate The optional due date for the to-do item.
 * @property creationDateTime The creation date and time of the to-do item.
 * @property isCompleted A boolean flag indicating whether the to-do item has been completed.
 * @property flag An optional integer flag, can be used for priority or other categorizations.
 */
@Entity(
    tableName = "todo_items",
    indices = [
        Index(value = ["isCompleted", "completedDateTime"]),
        Index(value = ["dueDate"]),
        Index(value = ["isCompleted", "dueDate"]),
        Index(value = ["creationDateTime"])
    ]
)
data class TodoItem(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val dueDate: LocalDate? = null,
    val creationDateTime: LocalDateTime = LocalDateTime.now(),
    val isCompleted: Boolean = false,
    val flag: Int = 0,
    val completedDateTime: LocalDateTime? = null,
    val notes: String = "",
    val startTime: LocalTime? = null,
    val endTime: LocalTime? = null,
    val reminderMode: TodoReminderMode? = null,
    val reminderOffsetMinutes: Int? = null,
    val reminderDayOffset: Int? = null,
    val reminderTime: LocalTime? = null,
    val reminderPersistent: Boolean = false,
    val reminderStrong: Boolean = false,
    val calendarEventId: Long? = null,
    val calendarSyncedAt: LocalDateTime? = null
)

fun TodoItem.reminderDateTime(): LocalDateTime? {
    return when (reminderMode) {
        TodoReminderMode.BeforeStart -> {
            val date = dueDate ?: return null
            val time = startTime ?: return null
            val offset = reminderOffsetMinutes ?: return null
            date.atTime(time).minusMinutes(offset.toLong())
        }

        TodoReminderMode.BeforeDueDate -> {
            val date = dueDate ?: return null
            val time = reminderTime ?: return null
            val dayOffset = reminderDayOffset ?: return null
            date.minusDays(dayOffset.toLong()).atTime(time)
        }

        null -> null
    }
}

const val EXTRA_DELETE_ID = "extra_delete_id"

const val EXTRA_TODO_ID = "todo_id"