package com.nevoit.cresto.data.todo

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalDateTime

/**
 * Represents a single to-do item entity for the Room database.
 *
 * @property id The unique identifier for the to-do item. Auto-generated by the database.
 * @property title The main text or title of the to-do item.
 * @property dueDate The optional due date for the to-do item.
 * @property creationDateTime The creation date and time of the to-do item.
 * @property isCompleted A boolean flag indicating whether the to-do item has been completed.
 * @property flag An optional integer flag, can be used for priority or other categorizations.
 */
@Entity(
    tableName = "todo_items",
    indices = [
        Index(value = ["isCompleted", "completedDateTime"]),
        Index(value = ["recurringRuleId"])
    ]
)
data class TodoItem(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val dueDate: LocalDate? = null,
    val creationDateTime: LocalDateTime = LocalDateTime.now(),
    val isCompleted: Boolean = false,
    val flag: Int = 0,
    val completedDateTime: LocalDateTime? = null,
    val recurringRuleId: Int? = null
)

const val EXTRA_DELETE_ID = "extra_delete_id"

const val EXTRA_TODO_ID = "todo_id"